/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gccGuardedLaunchSol from "./GCC.GuardedLaunch.sol";
export type { gccGuardedLaunchSol };
import type * as glowGuardedLaunchSol from "./Glow.GuardedLaunch.sol";
export type { glowGuardedLaunchSol };
