/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockGCA__factory } from "./MockGCA__factory";
export { MockMinerPoolAndGCA__factory } from "./MockMinerPoolAndGCA__factory";
export { MockSalaryHelper__factory } from "./MockSalaryHelper__factory";
//# sourceMappingURL=index.js.map