/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VetoCouncil } from "./VetoCouncil";
export type { VetoCouncilSalaryHelper } from "./VetoCouncilSalaryHelper";
