"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IHoldingContract__factory = exports.HoldingContract__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var HoldingContract__factory_1 = require("./HoldingContract__factory");
Object.defineProperty(exports, "HoldingContract__factory", { enumerable: true, get: function () { return HoldingContract__factory_1.HoldingContract__factory; } });
var IHoldingContract__factory_1 = require("./IHoldingContract__factory");
Object.defineProperty(exports, "IHoldingContract__factory", { enumerable: true, get: function () { return IHoldingContract__factory_1.IHoldingContract__factory; } });
//# sourceMappingURL=index.js.map